### ISSUE TITLE
Anything to add?

### ISSUE THREAD

**Issue by nofxx** [mongoid/mongoid-geospatial#8]
Every function the old spacial had is here, with the exception of distance, which is delegated to external libraries. And some new cool stuff like bbox and new geometry types.

Now it's time to try and think what can be improved. Waiting for suggestions.

**Comment by nofxx** [comment]
@Exoth Totally missed  you comment man, sorry! Gonna check!

**Comment by nofxx** [comment]
Helper for leaflet?
One thing I'm doing over and over is:
```
{ t: thing.name, m: thing.geom.to_a.reverse }
```
* A lil helper for geom... MongoDB uses X, Y,  leaflet,google uses Y, X.
* Build that hash for maps (t for label, m for point iirc that's leaflet convention)

@kristianmandrup thoughts?

**Comment by kristianmandrup** [comment]
List 3 ways you think it could be beat done, most convenient while maintaining flexibility. Then we decide ;)

**Comment by nofxx** [comment]
Added Point#reverse.  So you dont need `.to_a.reverse`

**Comment by kristianmandrup** [comment]
Awesome!

**Comment by Exoth** [comment]
Sorry guys that I haven't managed to do the pull request in these like 3 years. Thanks for bringing it up.

**Comment by nofxx** [comment]
@Exoth was thinking in your idea, what do  you think:

```
  field  :foo,  type: Point

  validates :foo, geospatial: { earth: true,  polygon: true }
```

earth -> (need better name) is it spherical, (-180..180)
polygon -> it is closed 
geometry -> only positive values valid +

**Comment by nofxx** [comment]
earth could be used with polygon*

**Comment by Exoth** [comment]
I guess that would be useful.

**Comment by Startouf** [comment]
Following @kristianmandrup remark on the Point namespace, until something is done I suggested the changes in the readme in #53 

I also think there should be better support for using lat/lng (instead of x and y or arrays) to avoid confusions with other libraries such as Google that use LatLng (cf my comment in the same PR)

For instance, I have monkeypatched the gem in an initializer to add the following methods. I would love to be able to call `model.coordinates.lat` or even `model.lat` (I often confuse which one of latitude/longitude is the horizontal/vertical direction anyways, so x/y doesn't help me much ^^")
```
module Mongoid
  module Geospatial
    class Point
      alias :lng :x
      alias :longitude :x
      alias :lat :y
      alias :latitude :y

      def to_latlng_a
        [lat, lng]
      end
    end
  end
end
```

**Comment by nofxx** [comment]
That's great. One thing, let's drop the `_a`? #to_latlng

**Comment by dblock** [comment]
Lets close this and open specific issues if anyone wants to? I'm going to spend some time cleaning things up.
